---
- name: Setup
  become: true
  ansible.builtin.import_tasks: setup.yaml

- name: Nvidia Setup (Use the edpm_accel_drivers role to install the NVIDIA driver in our VM)
  ansible.builtin.include_role:
    name: osp.edpm.edpm_accel_drivers

- name: (Temp) Install NVIDIA drivers with custom URL rpm
  become: true
  ansible.builtin.yum_repository:
    name: nvidia-rhel
    description: nvidia drivers for rhel
    baseurl: "{{ edpm_accel_drivers_nvidia_repo_url }}/$basearch/"
    gpgcheck: true
    gpgkey: "{{ edpm_accel_drivers_nvidia_repo_gpgkey }}"

- name: Install nvidia-container-toolkit
  ansible.builtin.dnf:
    use_backend: dnf4
    name: nvidia-container-toolkit
    state: present

- name: Reboot the VM to find the installed drivers
  ansible.builtin.reboot:
    reboot_timeout: 600
  become: true
  when:
    - ansible_distribution == "RedHat"
    - gpu_validation_mode == "mig"

- name: Check GPUs
  ansible.builtin.import_tasks: gpus.yaml
- name: GPUs Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: gpus_assertions.yaml
  ignore_errors: true

- name: Check NVIDIA
  ansible.builtin.import_tasks: nvidia.yaml
- name: NVIDIA Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: nvidia_assertions.yaml
  ignore_errors: true

- name: Check CUDA libs
  ansible.builtin.import_tasks: cuda.yaml
- name: CUDA Assertions  # noqa: ignore-errors
  ansible.builtin.import_tasks: cuda_assertions.yaml
  ignore_errors: true

- name: Check vllm
  ansible.builtin.import_tasks: vllm.yaml
  when: gpu_validation_model_tests_enabled | bool

- name: Cleanup
  become: true
  ansible.builtin.import_tasks: cleanup.yaml
