---
- name: Set DNS server using nmcli if gpu_validation_dns_server is set
  ansible.builtin.shell: |
    nmcli con mod "System eth0" ipv4.dns "{{ gpu_validation_dns_server }}" ipv4.ignore-auto-dns yes
    nmcli con up "System eth0"
  when: gpu_validation_dns_server != ""
  changed_when: true

- name: Install needed driver dependency packages for RHEL
  when:
    - ansible_distribution == "RedHat"
    - gpu_validation_mode == "mig"
  block:
    - name: Run repo-setup for RHEL VMs
      ansible.builtin.include_role:
        name: cifmw.general.repo_setup
        tasks_from: rhos_release

    - name: Add EPEL repository for DKMS (UNSUPPORTED)
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: "https://download.fedoraproject.org/pub/epel/{{ ansible_facts['distribution_major_version'] }}/Everything/$basearch/"
        enabled: 1
        gpgcheck: 1
        gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"

    - name: Install DKMS (Not supported)
      ansible.builtin.dnf:
        use_backend: dnf4
        name:
          - dkms
          - kernel-devel
          - kernel-headers
        state: present

- name: Install pciutils package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: pciutils
    state: present

- name: Install pip package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: python-pip
    state: present

- name: Install podman package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: podman
    state: present

- name: Copy scripts from local to RHEL AI machine
  ansible.builtin.copy:
    src: "{{ role_path }}/files/scripts"
    dest: /tmp
    mode: "1777"
