---
- name: Check if image with the correct name already exists in Glance
  openstack.cloud.image_info:
    name: "{{ gpu_validation_image_name }}"
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
  register: _gpu_validation_image_info

- name: Set fact if image exists
  ansible.builtin.set_fact:
    _gpu_validation_image_exists: "{{ (_gpu_validation_image_info.images | length) > 0 }}"

- name: Download VM image
  ansible.builtin.get_url:
    url: "{{ gpu_validation_image_url }}"
    dest: "/tmp/{{ gpu_validation_image_url | basename }}"
    mode: '0644'
  when: not _gpu_validation_image_exists

- name: Create glance image from GPU validation download source
  openstack.cloud.image:
    name: "{{ gpu_validation_image_name }}"
    container_format: bare
    disk_format: qcow2
    filename: "/tmp/{{ gpu_validation_image_url | basename }}"
    visibility: public
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
  when: not _gpu_validation_image_exists

- name: Reset extra_specs based GPU mode
  ansible.builtin.set_fact:
    gpu_validation_extra_specs:
      "resources:VGPU": "1"
  when: gpu_validation_mode == "mig"

- name: Create flavor for GPU validation
  openstack.cloud.compute_flavor:
    name: "{{ gpu_validation_flavor_name }}"
    ram: "{{ gpu_validation_flavor_ram }}"
    vcpus: "{{ gpu_validation_flavor_vcpus }}"
    disk: "{{ gpu_validation_flavor_disk }}"
    extra_specs: "{{ gpu_validation_extra_specs }}"
    ca_cert: "{{ gpu_validation_ca_cert_path }}"
